/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lazybox_sidebar: [{ type: "autogenerated", dirName: "." }],
  api_sdk_kit_sidebar: [{ type: "autogenerated", dirName: "." }],
  aws_ses_bounce_sidebar: [{ type: "autogenerated", dirName: "." }],
  boilerplate_generator_sidebar: [{ type: "autogenerated", dirName: "." }],
  simple_files_sidebar: [{ type: "autogenerated", dirName: "." }],
  simple_maintenance_sidebar: [{ type: "autogenerated", dirName: "." }],
  simple_secrets_sidebar: [{ type: "autogenerated", dirName: "." }],
  starter_kit_sidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
